name: leitmotiv
channels:
  - conda-forge
  - pytorch
  - default
dependencies:
  - python=3.7
  - mkl-service
  - numpy
  - pytorch
  - pillow
  - pytables
  - scikit-image
  - scikit-learn
  - scipy
  - pip:
    - click
    - flask
    - libsass
    - peewee
    - ruamel.yaml
    - tqdm
    - -e .
