name: leitmotiv
channels:
  - conda-forge
  - pytorch
  - default
dependencies:
  - mkl-service=1.1.2
  - numpy=1.15.4
  - pytorch=1.0
  - python=3.7
  - pillow=5.4.1
  - pytables=3.4.4
  - scikit-image=0.14.1
  - scikit-learn=0.20.2
  - scipy=1.1.0
  - pip:
    - click
    - flask
    - libsass
    - peewee
    - ruamel.yaml
    - tqdm
